apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-secret
  namespace: default
type: Opaque
stringData:
  # Base64 encode these in production!
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
